# Generated by Django 5.2.15 on 2026-06-30 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(default='XOF', max_length=3)),
                ('methode', models.CharField(choices=[('paypal', 'PayPal'), ('mtn', 'MTN Mobile Money'), ('moov', 'Moov Money')], max_length=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('echouee', 'Échouée'), ('remboursee', 'Remboursée')], default='en_attente', max_length=15)),
                ('reference_externe', models.CharField(blank=True, help_text='ID PayPal ou ID transaction Mobile Money', max_length=120)),
                ('telephone', models.CharField(blank=True, help_text='Requis pour Mobile Money', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='payments_tr_content_dc666b_idx'), models.Index(fields=['statut'], name='payments_tr_statut_7ec9f7_idx')],
            },
        ),
    ]
