# Generated by Django 5.1.4 on 2026-06-13 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('author', 'Auteur'), ('visitor', 'Visiteur')], default='visitor', max_length=20, verbose_name='Rôle')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biographie')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Photo de profil')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('speciality', models.CharField(blank=True, max_length=200, null=True, verbose_name='Spécialité')),
                ('institution', models.CharField(blank=True, max_length=200, null=True, verbose_name='Institution')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
    ]
