# Generated by Django 5.1.4 on 2026-06-21 00:28

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[accounts.models.validate_avatar], verbose_name='Photo de profil'),
        ),
    ]
