# Generated by Django 5.1 on 2026-06-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Titre affiché dans Google (max 60 caractères). Si vide, le titre principal est utilisé tronqué.', max_length=60, null=True, verbose_name='Titre SEO'),
        ),
    ]
