# Generated by Django 5.2.15 on 2026-06-30 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(default='fas fa-box', help_text='Classe Font Awesome', max_length=50)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Catégorie produit',
                'verbose_name_plural': 'Catégories produits',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Panier',
            },
        ),
        migrations.CreateModel(
            name='ZoneLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('frais', models.DecimalField(decimal_places=2, max_digits=8)),
                ('delai_jours', models.PositiveIntegerField(default=3, help_text='Délai en jours ouvrables')),
            ],
            options={
                'verbose_name': 'Zone de livraison',
                'verbose_name_plural': 'Zones de livraison',
                'ordering': ['frais'],
            },
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse_ligne1', models.CharField(max_length=255)),
                ('adresse_ligne2', models.CharField(blank=True, max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(default='Togo', max_length=100)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to=settings.AUTH_USER_MODEL)),
                ('zone_livraison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boutique.zonelivraison')),
            ],
            options={
                'verbose_name': 'Adresse',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('confirme', 'Confirmée'), ('en_preparation', 'En préparation'), ('expedie', 'Expédiée'), ('livre', 'Livrée'), ('annule', 'Annulée')], default='en_attente', max_length=20)),
                ('mode_paiement', models.CharField(choices=[('virement', 'Virement bancaire'), ('a_la_livraison', 'Paiement à la livraison'), ('mobile_money', 'Mobile Money (Flooz/T-Money)')], default='virement', max_length=20)),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sous_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('suivi', models.CharField(blank=True, help_text='Numéro de suivi transporteur', max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('adresse_livraison', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='boutique.adresse')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description_courte', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='boutique/produits/')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_promo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('poids_kg', models.DecimalField(decimal_places=3, default=0, help_text='Poids en kg (pour frais de port)', max_digits=6)),
                ('disponible', models.BooleanField(default=True)),
                ('en_vedette', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='boutique.categorieproduit')),
            ],
            options={
                'verbose_name': 'Produit',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=200)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='boutique.commande')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boutique.produit')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
            },
        ),
        migrations.CreateModel(
            name='LignePanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='boutique.panier')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.produit')),
            ],
            options={
                'verbose_name': 'Ligne de panier',
                'unique_together': {('panier', 'produit')},
            },
        ),
    ]
