# Generated by Django 5.2.15 on 2026-06-30 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(default='fas fa-graduation-cap', max_length=50)),
            ],
            options={
                'verbose_name': 'Catégorie formation',
                'verbose_name_plural': 'Catégories formations',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sous_titre', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('objectifs', models.TextField(help_text='Objectifs pédagogiques (un par ligne)')),
                ('type_formation', models.CharField(choices=[('presentiel', 'Présentiel'), ('en_ligne', 'En ligne'), ('hybride', 'Hybride')], default='hybride', max_length=15)),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('expert', 'Expert')], default='debutant', max_length=15)),
                ('duree_heures', models.PositiveIntegerField(default=0, help_text='Durée totale en heures')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_promo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='formations/covers/')),
                ('certificat', models.BooleanField(default=True, help_text='Certificat de fin de formation')),
                ('en_vedette', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('prerequis', models.TextField(blank=True, help_text='Prérequis (un par ligne)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='formations.categorieformation')),
            ],
            options={
                'verbose_name': 'Formation',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ModuleFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('duree_minutes', models.PositiveIntegerField(default=0)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='formations.formation')),
            ],
            options={
                'verbose_name': 'Module',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_lecon', models.CharField(choices=[('video', 'Vidéo'), ('pdf', 'PDF / Document'), ('quiz', 'Quiz'), ('texte', 'Texte')], default='texte', max_length=10)),
                ('contenu', models.TextField(blank=True, help_text='Contenu texte ou URL vidéo/PDF')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='formations/lecons/')),
                ('duree_minutes', models.PositiveIntegerField(default=0)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('gratuite', models.BooleanField(default=False, help_text='Leçon accessible sans inscription')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='formations.moduleformation')),
            ],
            options={
                'verbose_name': 'Leçon',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='SessionPresentiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('lieu', models.CharField(max_length=300)),
                ('ville', models.CharField(max_length=100)),
                ('places_max', models.PositiveIntegerField(default=20)),
                ('statut', models.CharField(choices=[('ouvert', 'Inscriptions ouvertes'), ('complet', 'Complet'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='ouvert', max_length=10)),
                ('informations', models.TextField(blank=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='formations.formation')),
            ],
            options={
                'verbose_name': 'Session présentiel',
                'verbose_name_plural': 'Sessions présentiel',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('profession', models.CharField(blank=True, max_length=200)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('confirme', 'Confirmée'), ('termine', 'Terminée'), ('annule', 'Annulée')], default='en_attente', max_length=15)),
                ('mode_paiement', models.CharField(choices=[('virement', 'Virement bancaire'), ('sur_place', 'Paiement sur place'), ('mobile_money', 'Mobile Money (Flooz/T-Money)')], default='virement', max_length=20)),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes_admin', models.TextField(blank=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='formations.formation')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions', to='formations.sessionpresentiel')),
            ],
            options={
                'verbose_name': 'Inscription',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='ProgressionLecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminee', models.BooleanField(default=False)),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.lecon')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progression leçon',
                'unique_together': {('utilisateur', 'lecon')},
            },
        ),
    ]
