# Generated by Django 5.1.4 on 2026-06-13 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('file', models.FileField(upload_to='resources/', verbose_name='Fichier')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('excel', 'Excel'), ('powerpoint', 'PowerPoint'), ('other', 'Autre')], default='pdf', max_length=20, verbose_name='Type de fichier')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='resources/thumbnails/', verbose_name='Miniature')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Téléchargements')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('is_public', models.BooleanField(default=True, verbose_name='Public')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='blog.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
                'ordering': ['-created_at'],
            },
        ),
    ]
