# Generated by Django 5.1.4 on 2026-06-21 00:28

import resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(upload_to='resources/', validators=[resources.models.validate_resource_file], verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='resources/thumbnails/', validators=[resources.models.validate_image_file], verbose_name='Miniature'),
        ),
    ]
